
package presentacion_editarViaje;

import Controles.IControlPantallas;
import dto.ParadaDTO;
import dto.ViajeDTO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author ferch
 */
public class editarParada extends javax.swing.JPanel {
private final IControlPantallas controlPantallas;
    private ViajeDTO viajeActual;
    private List<ParadaDTO> paradasEditables;
    
    private JTextField txtDireccionNueva;
    private JTextField txtPrecioNuevo;
    private JPanel panelAnadirParada;   
    private JScrollPane scrollPaneParadas;
    
    /**
     * Creates new form editarParada
     * @param controlPantallas
     */
    public editarParada(IControlPantallas controlPantallas) {
        this.controlPantallas = controlPantallas;
        
        this.viajeActual = controlPantallas.obtenerViajeParaEdicion();

        if (this.viajeActual == null) {
            JOptionPane.showMessageDialog(null, "No hay un viaje seleccionado para editar paradas. Regresando al menu.", "Error", JOptionPane.ERROR_MESSAGE);
            this.controlPantallas.mostrarMenuConductor();
        } else {
            this.paradasEditables = new ArrayList<>(this.viajeActual.getParadas());
            initComponents();
            configurarPanelDinamico(); 
            mostrarParadasEditables(); 
        }
    }
    
    /**
     * Configura el panel de paradas scroll y añade los campos de adicion.
     */
    private void configurarPanelDinamico() {
       // Envolver mostrarParadasPanel en un JScrollPane
        scrollPaneParadas = new JScrollPane(mostrarParadasPanel);
        scrollPaneParadas.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPaneParadas.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneParadas.setBorder(BorderFactory.createTitledBorder("Paradas Actuales"));
        
        // Usar BoxLayout para apilar filas
        mostrarParadasPanel.setLayout(new BoxLayout(mostrarParadasPanel, BoxLayout.Y_AXIS));

        jPanel2.remove(mostrarParadasPanel); 

        jPanel2.add(scrollPaneParadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 100, 549, 308));

        agregarParadaBtn.setBounds(580, 420, 100, 40); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mostrarParadasPanel = new javax.swing.JPanel();
        agregarParadaBtn = new javax.swing.JButton();
        regresarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        guardarParadasBtn1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 109, 182));
        jPanel1.setMinimumSize(new java.awt.Dimension(1167, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 109, 182));

        mostrarParadasPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mostrarParadasPanelLayout = new javax.swing.GroupLayout(mostrarParadasPanel);
        mostrarParadasPanel.setLayout(mostrarParadasPanelLayout);
        mostrarParadasPanelLayout.setHorizontalGroup(
            mostrarParadasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        mostrarParadasPanelLayout.setVerticalGroup(
            mostrarParadasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        agregarParadaBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        agregarParadaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boton.jpg"))); // NOI18N
        agregarParadaBtn.setBorder(null);
        agregarParadaBtn.addActionListener(this::agregarParadaBtnActionPerformed);

        regresarBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        regresarBtn.setText("Regresar");
        regresarBtn.setBorder(null);
        regresarBtn.addActionListener(this::regresarBtnActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EDITAR PARADAS");

        guardarParadasBtn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        guardarParadasBtn1.setText("GuardarParadas");
        guardarParadasBtn1.setBorder(null);
        guardarParadasBtn1.addActionListener(this::guardarParadasBtn1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(agregarParadaBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(mostrarParadasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(642, Short.MAX_VALUE)
                    .addComponent(guardarParadasBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(mostrarParadasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(agregarParadaBtn)
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(499, Short.MAX_VALUE)
                    .addComponent(guardarParadasBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 870, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1069, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Dibujar la lista de paradas editables y eliminables dentro del panel de scroll.
     */
    private void mostrarParadasEditables() {
     if (this.viajeActual == null) return; 
      
      mostrarParadasPanel.removeAll();

      final int ROW_HEIGHT = 60;
      final int PANEL_WIDTH = 540; 
      int preferredHeight = paradasEditables.size() * ROW_HEIGHT;
      
      mostrarParadasPanel.setPreferredSize(new Dimension(549, preferredHeight));
      
        for (int i = 0; i < paradasEditables.size(); i++) {
            ParadaDTO parada = paradasEditables.get(i);
            int paradaIndex = i + 1;
            boolean isOrigin = (i == 0);

            // Panel Contenedor de la fila
            JPanel panelElemento = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 5));
            panelElemento.setBackground(new Color(255, 255, 255));

            panelElemento.setMaximumSize(new Dimension(PANEL_WIDTH, ROW_HEIGHT)); 
            panelElemento.setMinimumSize(new Dimension(PANEL_WIDTH, ROW_HEIGHT));
            panelElemento.setPreferredSize(new Dimension(PANEL_WIDTH, ROW_HEIGHT));
            panelElemento.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(204, 204, 204)));

            // Etiqueta
            JLabel lblParada = new JLabel(isOrigin ? "ORIGEN:" : "Parada #" + paradaIndex + ":");
            lblParada.setFont(new Font("Segoe UI", Font.BOLD, 14));
            lblParada.setPreferredSize(new Dimension(80, 30)); 

            // Campo Direccion
            JTextField txtDireccion = new JTextField(parada.getDirección());
            txtDireccion.setPreferredSize(new Dimension(160, 30)); 
            txtDireccion.setName("txtDireccion-" + i);
            
            // Campo Precio
            JTextField txtPrecio = new JTextField(String.valueOf(parada.getPrecio()));
            txtPrecio.setPreferredSize(new Dimension(70, 30));
            txtPrecio.setName("txtPrecio-" + i); 

            // Botón Eliminar
            JButton btnEliminar = new JButton(isOrigin ? "Fijo" : "Eliminar");
            btnEliminar.setBackground(isOrigin ? Color.LIGHT_GRAY : new Color(200, 0, 0));
            btnEliminar.setForeground(Color.WHITE);
            btnEliminar.setFont(new Font("Segoe UI", Font.BOLD, 10));
            btnEliminar.setPreferredSize(new Dimension(70, 30));
            btnEliminar.setActionCommand(String.valueOf(i)); 
            btnEliminar.addActionListener(this::btnEliminarParadaActionPerformed);
            btnEliminar.setEnabled(!isOrigin);

            // Restriccion: Origen no editable
            if (isOrigin) { 
                txtDireccion.setEditable(false);
                txtPrecio.setEditable(false);
            }

            // Ensamblaje
            panelElemento.add(lblParada);
            panelElemento.add(new JLabel("Dir:"));
            panelElemento.add(txtDireccion);
            panelElemento.add(new JLabel("Precio:"));
            panelElemento.add(txtPrecio);
            panelElemento.add(btnEliminar);
            
            mostrarParadasPanel.add(panelElemento);
        }
        

        mostrarParadasPanel.revalidate();
        mostrarParadasPanel.repaint();
        
        SwingUtilities.invokeLater(() -> scrollPaneParadas.getVerticalScrollBar().setValue(0));
    }
    
    /**
     * Metodo para manejar la eliminacion de una parada.
     */
    private void btnEliminarParadaActionPerformed(ActionEvent evt) {
        try {
            int index = Integer.parseInt(evt.getActionCommand());
            
            if (index == 0) {
                 JOptionPane.showMessageDialog(this, "No se puede eliminar la parada de origen.", "Restriccion", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            this.paradasEditables.remove(index);
            mostrarParadasEditables();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar la parada: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void guardarParadasTemporalmente() {
         try {
            List<ParadaDTO> nuevasParadas = new ArrayList<>();
            
            // Recoleccion de datos de la UI
            for (Component comp : mostrarParadasPanel.getComponents()) {
                if (comp instanceof JPanel) {
                    JPanel panelParada = (JPanel) comp;
                    
                    String direccion = null;
                    String precioStr = null;
                    
                    for (Component innerComp : panelParada.getComponents()) {
                        if (innerComp instanceof JTextField) {
                            JTextField textField = (JTextField) innerComp;
                            if (textField.getName() != null) {
                                if (textField.getName().startsWith("txtDireccion")) {
                                    direccion = textField.getText().trim();
                                } else if (textField.getName().startsWith("txtPrecio")) {
                                    precioStr = textField.getText().trim();
                                }
                            }
                        }
                    }
                    
                    if (direccion == null || precioStr == null) continue;

                    double precio = Double.parseDouble(precioStr);
                    
                    ParadaDTO paradaEditada = new ParadaDTO(direccion, precio);
                    if (nuevasParadas.isEmpty() && !paradasEditables.isEmpty() && paradasEditables.get(0).getId() != null) {
                        paradaEditada.setId(paradasEditables.get(0).getId());
                    }
                    
                    nuevasParadas.add(paradaEditada);
                }
            }
            
            // Sincroniza el ViajeDTO temporal en el controlador con los cambios (eliminaciones/ediciones)
            controlPantallas.actualizarParadasViaje(nuevasParadas);
            
            // Resincroniza la lista local (paradasEditables) para estar limpia si el usuario navega
            this.paradasEditables = new ArrayList<>(controlPantallas.obtenerViajeParaEdicion().getParadas());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error de formato. Asegurese de que todos los precios sean numeros validos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }}
    
    private void agregarParadaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarParadaBtnActionPerformed
        guardarParadasTemporalmente();
        controlPantallas.mostrarAgregarParada();
    }//GEN-LAST:event_agregarParadaBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        // Vuelve a la pantalla de edicion de viaje.
    
        controlPantallas.mostrarEditarViaje();
       
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void guardarParadasBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarParadasBtn1ActionPerformed
      try {
            List<ParadaDTO> paradasApersisitir = new ArrayList<>();

            for (Component comp : mostrarParadasPanel.getComponents()) {
                if (comp instanceof JPanel) {
                    JPanel panelParada = (JPanel) comp;
                    
                    String direccion = null;
                    String precioStr = null;
                    
                    for (Component innerComp : panelParada.getComponents()) {
                        if (innerComp instanceof JTextField) {
                            JTextField textField = (JTextField) innerComp;
                            if (textField.getName() != null) {
                                if (textField.getName().startsWith("txtDireccion")) {
                                    direccion = textField.getText().trim();
                                } else if (textField.getName().startsWith("txtPrecio")) {
                                    precioStr = textField.getText().trim();
                                }
                            }
                        }
                    }
                    
                    if (direccion == null || precioStr == null) continue;

                    if (direccion.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "La direccion de una parada no puede estar vacía.", "Error de Validacion", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    double precio = Double.parseDouble(precioStr);
                    if (precio < 0) {
                        JOptionPane.showMessageDialog(this, "El precio de una parada debe ser positivo.", "Error de Validacion", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    ParadaDTO paradaEditada = new ParadaDTO(direccion, precio);
                    if (paradasApersisitir.isEmpty() && !paradasEditables.isEmpty() && paradasEditables.get(0).getId() != null) {
                        paradaEditada.setId(paradasEditables.get(0).getId());
                    }
                    
                    paradasApersisitir.add(paradaEditada);
                }
            }
            
            if (paradasApersisitir.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El viaje debe tener al menos una parada (Origen).", "Validacion", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Llama a la capa de control para actualizar el ViajeDTO temporal
            controlPantallas.actualizarParadasViaje(paradasApersisitir);

            this.paradasEditables = new ArrayList<>(this.viajeActual.getParadas());
            mostrarParadasEditables();
            
            JOptionPane.showMessageDialog(this,
                    "¡Paradas guardadas con exito! Los cambios se reflejaran al guardar el viaje.",
                    "Exito",
                    JOptionPane.INFORMATION_MESSAGE);
            
            // Navegar a la pantalla de edicion de viaje
            controlPantallas.mostrarEditarViaje();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error de formato. Asegurese de que todos los precios sean numeros validos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar paradas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarParadasBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarParadaBtn;
    private javax.swing.JButton guardarParadasBtn1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mostrarParadasPanel;
    private javax.swing.JButton regresarBtn;
    // End of variables declaration//GEN-END:variables
}
