
package presentacion_editarViaje;

import Controles.IControlPantallas;
import dto.ParadaDTO;
import dto.ViajeDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ferch
 */
public class editarViaje extends javax.swing.JPanel {

     private final IControlPantallas controlPantallas;
     private ViajeDTO viajeActual; 
    /**
     * Creates new form editarViaje
     */
    public editarViaje(IControlPantallas controlPantallas) {
        this.controlPantallas = controlPantallas;

        this.viajeActual = controlPantallas.obtenerViajeParaEdicion();

        if (this.viajeActual == null) {
            // Si no hay viaje, muestra el error y regresa al menú de conductor
            JOptionPane.showMessageDialog(null, "No hay un viaje seleccionado para editar. Regresando al menu.", "Error", JOptionPane.ERROR_MESSAGE);
            this.controlPantallas.mostrarMenuConductor();
            this.viajeActual = new ViajeDTO(); 
        } else {
            // Si el viaje existe, inicializa la interfaz y carga los datos
            initComponents();
            cargarDatosViaje();
            mostrarParadas();
        }
    }
    
    private void cargarDatosViaje() {
        origenTField.setText(viajeActual.getOrigen());
        destinoTField.setText(viajeActual.getDestino());
        PrecioTextField.setText(String.valueOf(viajeActual.getPrecioTotal()));
        fechaHora.getDatePicker().setDate(viajeActual.getFecha());
        fechaHora.getTimePicker().setTime(viajeActual.getHora());
        
        // El origen no se debe poder editar
        origenTField.setEditable(false);
    }
    
     // metodo para mostrar las paradas en el scroll
    private void mostrarParadas() {
        if (viajeActual == null || viajeActual.getParadas() == null) return;
        
        jPanelParadas.removeAll();
        jPanelParadas.setLayout(new BoxLayout(jPanelParadas, BoxLayout.Y_AXIS));
        
        for (int i = 0; i < viajeActual.getParadas().size(); i++) {
            ParadaDTO parada = viajeActual.getParadas().get(i);
            
            JPanel panelInfo = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 5));
            panelInfo.setBackground(new Color(240, 240, 240));
            panelInfo.setPreferredSize(new Dimension(390, 40));
            panelInfo.setMaximumSize(new Dimension(390, 40));
            panelInfo.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

            JLabel lblIndex = new JLabel("#" + (i + 1) + ": ");
            lblIndex.setFont(new Font("Segoe UI", Font.BOLD, 12));
            
            JLabel lblInfo = new JLabel(parada.getDirección() + " ($" + parada.getPrecio() + ")");
            
            panelInfo.add(lblIndex);
            panelInfo.add(lblInfo);
            
            jPanelParadas.add(panelInfo);
        }
        
        jPanelParadas.revalidate();
        jPanelParadas.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        origenTField = new javax.swing.JTextField();
        destinoTField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaHora = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel1 = new javax.swing.JLabel();
        guardarCambiosViajeBtn = new javax.swing.JButton();
        regresarMenuVehiculosBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PrecioTextField = new javax.swing.JTextField();
        jScrollPaneParadas = new javax.swing.JScrollPane();
        jPanelParadas = new javax.swing.JPanel();
        editarParadasBtn1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 109, 182));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 109, 182));

        destinoTField.addActionListener(this::destinoTFieldActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Destino:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Origen:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha y hora:");

        fechaHora.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDITAR VIAJE");

        guardarCambiosViajeBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        guardarCambiosViajeBtn.setText("Guardar Cambios");
        guardarCambiosViajeBtn.setBorder(null);
        guardarCambiosViajeBtn.addActionListener(this::guardarCambiosViajeBtnActionPerformed);

        regresarMenuVehiculosBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        regresarMenuVehiculosBtn.setText("Regresar");
        regresarMenuVehiculosBtn.setBorder(null);
        regresarMenuVehiculosBtn.addActionListener(this::regresarMenuVehiculosBtnActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio:");

        PrecioTextField.addActionListener(this::PrecioTextFieldActionPerformed);

        jPanelParadas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelParadasLayout = new javax.swing.GroupLayout(jPanelParadas);
        jPanelParadas.setLayout(jPanelParadasLayout);
        jPanelParadasLayout.setHorizontalGroup(
            jPanelParadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanelParadasLayout.setVerticalGroup(
            jPanelParadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        jScrollPaneParadas.setViewportView(jPanelParadas);

        editarParadasBtn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        editarParadasBtn1.setText("Editar Paradas");
        editarParadasBtn1.setBorder(null);
        editarParadasBtn1.addActionListener(this::editarParadasBtn1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(regresarMenuVehiculosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarCambiosViajeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editarParadasBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PrecioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origenTField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(destinoTField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPaneParadas, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(editarParadasBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(origenTField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(24, 24, 24)
                                .addComponent(destinoTField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PrecioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPaneParadas))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarMenuVehiculosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarCambiosViajeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 1000, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void destinoTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoTFieldActionPerformed

    private void guardarCambiosViajeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosViajeBtnActionPerformed
        // Validar y guardar los datos del viaje antes de continuar

        String origen = origenTField.getText().trim();
        String destino = destinoTField.getText().trim();
        LocalDate fecha = fechaHora.getDatePicker().getDate();
        LocalTime hora = fechaHora.getTimePicker().getTime();
        String precioStr = PrecioTextField.getText().trim();

        double precioBase;
        if (precioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor ingrese un precio.",
                "Campo Requerido",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            precioBase = Double.parseDouble(precioStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "El precio debe ser un numero valido.",
                "Error de Formato",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (origen.isEmpty() || destino.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor complete todos los campos",
                "Campos incompletos",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        //validacion, origen y destino iguales
        if (origen.equalsIgnoreCase(destino)) {
            JOptionPane.showMessageDialog(this, "El Origen y el Destino no pueden ser la misma ubicacion.", "Dato Invalido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // validacion de tipo de dato origen y destino solo con texto
        if (origen.matches(".*\\d.*") || destino.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "El Origen y Destino no deben contener números. Ingrese solo texto.", "Dato Invalido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar fecha y hora
        if (fechaHora.getDateTimeStrict() == null) {
            JOptionPane.showMessageDialog(this,
                "Por favor seleccione una fecha y hora válida",
                "Fecha inválida",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que la fecha no sea en el pasado
        if (fechaHora.getDateTimeStrict().isBefore(java.time.LocalDateTime.now())) {
            JOptionPane.showMessageDialog(this,
                "La fecha y hora del viaje no puede ser en el pasado",
                "Fecha inválida",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Crear DTO modificado para guardar los datos generales
        ViajeDTO viajeModificado = new ViajeDTO();
        viajeModificado.setId(viajeActual.getId());
        viajeModificado.setOrigen(origen); 
        viajeModificado.setDestino(destino);
        viajeModificado.setFecha(fecha);
        viajeModificado.setHora(hora);
        viajeModificado.setPrecioTotal(precioBase);
        
        // Llamar al Control para guardar los cambios generales
        controlPantallas.guardarCambiosViaje(viajeModificado);

        //  Mostrar el mensaje de confirmacion solicitado
        JOptionPane.showMessageDialog(this,
                "El viaje ha sido modificado con exito!!\nPor favor presione Aceptar para volver al menu principal.",
                "Cambios guardados con exito",
                JOptionPane.INFORMATION_MESSAGE);
        
        // 4. Navegar de vuelta al menú
        controlPantallas.mostrarMenuConductor();

    }//GEN-LAST:event_guardarCambiosViajeBtnActionPerformed

    private void regresarMenuVehiculosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarMenuVehiculosBtnActionPerformed
        // TODO add your handling code here:
        controlPantallas.mostrarDetallesViaje();
    }//GEN-LAST:event_regresarMenuVehiculosBtnActionPerformed

    private void PrecioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioTextFieldActionPerformed

    private void editarParadasBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarParadasBtn1ActionPerformed
        controlPantallas.mostrarEditarParadas();
    }//GEN-LAST:event_editarParadasBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PrecioTextField;
    private javax.swing.JTextField destinoTField;
    private javax.swing.JButton editarParadasBtn1;
    private com.github.lgooddatepicker.components.DateTimePicker fechaHora;
    private javax.swing.JButton guardarCambiosViajeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelParadas;
    private javax.swing.JScrollPane jScrollPaneParadas;
    private javax.swing.JTextField origenTField;
    private javax.swing.JButton regresarMenuVehiculosBtn;
    // End of variables declaration//GEN-END:variables
}
