/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import Controles.IControlPantallas;
import dto.ViajeDTO;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author adell
 */
public class detallesViaje extends javax.swing.JPanel {

    private final IControlPantallas controlPantallas;

    /**
     * Creates new form detallesViaje
     * @param controlPantallas
     * @param viaje
     */
    public detallesViaje(IControlPantallas controlPantallas, ViajeDTO viaje) {
        this.controlPantallas = controlPantallas;

        initComponents();
        mostrarDatosViaje(viaje);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDestino = new javax.swing.JLabel();
        btnCancelarViaje = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtOrigen = new javax.swing.JTextField();
        lblClientes = new javax.swing.JLabel();
        txtClientes = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnEditarViaje = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 109, 182));
        setMinimumSize(new java.awt.Dimension(1080, 648));
        setPreferredSize(new java.awt.Dimension(1080, 640));

        lblDestino.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(255, 255, 255));
        lblDestino.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDestino.setText("Destino:");
        lblDestino.setToolTipText("");

        btnCancelarViaje.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarViaje.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancelarViaje.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarViaje.setText("CANCELAR VIAJE");
        btnCancelarViaje.setBorder(null);
        btnCancelarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarViajeActionPerformed(evt);
            }
        });

        // Configuracion del boton de editarViaje
        btnEditarViaje.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarViaje.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEditarViaje.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarViaje.setText("EDITAR VIAJE");
        btnEditarViaje.setBorder(null);
        btnEditarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarViajeActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("DETALLES DEL VIAJE");

        lblOrigen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblOrigen.setForeground(new java.awt.Color(255, 255, 255));
        lblOrigen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOrigen.setText("Inicio:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("Fecha:");

        lblHora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHora.setText("Hora:");

        txtDestino.setBackground(new java.awt.Color(0, 109, 182));
        txtDestino.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDestino.setForeground(new java.awt.Color(255, 255, 255));
        txtDestino.setBorder(null);

        txtFecha.setBackground(new java.awt.Color(0, 109, 182));
        txtFecha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setBorder(null);

        txtHora.setBackground(new java.awt.Color(0, 109, 182));
        txtHora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setBorder(null);

        txtOrigen.setBackground(new java.awt.Color(0, 109, 182));
        txtOrigen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtOrigen.setForeground(new java.awt.Color(255, 255, 255));
        txtOrigen.setBorder(null);

        lblClientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblClientes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClientes.setText("Clientes:");

        txtClientes.setBackground(new java.awt.Color(0, 109, 182));
        txtClientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtClientes.setForeground(new java.awt.Color(255, 255, 255));
        txtClientes.setBorder(null);

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("VOLVER");
        btnVolver.setBorder(null);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFecha)
                            .addComponent(lblOrigen)
                            .addComponent(lblDestino)
                            .addComponent(lblHora)
                            .addComponent(lblClientes))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(232, 232, 232))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(btnEditarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(btnCancelarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE) // Botón Cancelar
                                                .addGap(190, 190, 190))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(51, Short.MAX_VALUE)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrigen))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestino))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHora))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblClientes))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancelarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEditarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarViajeActionPerformed
        try {
            ViajeDTO viaje = controlPantallas.obtenerViajeTemporal();
            if (viaje == null || viaje.getId() == null) {
                JOptionPane.showMessageDialog(this,
                    "No hay un viaje seleccionado",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            int montoAdeudo = controlPantallas.obtenerAdeudoPendiente(viaje.getId());

            String mensaje;
            if (montoAdeudo > 0) {
                mensaje = String.format(
                    "Al cancelar este viaje se le cobrará un adeudo de $%d pesos.\n\n¿Está seguro de que desea cancelar este viaje?",
                    montoAdeudo
                );
            } else {
                mensaje = "¿Está seguro de que desea cancelar este viaje?\n\nNo se generará ningún adeudo.";
            }

            int confirmacion = JOptionPane.showConfirmDialog(this,
                mensaje,
                "Confirmar Cancelación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                controlPantallas.confirmarCancelacionViaje();

                if (montoAdeudo > 0) {
                    JOptionPane.showMessageDialog(this,
                        String.format("Viaje cancelado exitosamente.\n\nSe ha registrado un adeudo de $%d pesos.", montoAdeudo),
                        "Viaje Cancelado",
                        JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Viaje cancelado exitosamente.",
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
                }

                controlPantallas.mostrarMenuConductor();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this,
                "Error al cancelar el viaje: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelarViajeActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        controlPantallas.mostrarMenuConductor();
    }//GEN-LAST:event_btnVolverActionPerformed
    
    //boton del caso de uso de editarViaje
    private void btnEditarViajeActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Llama a la Fachada para validar si la edicion es segura
            boolean esEdicionSegura = controlPantallas.validarEdicionSegura(); 
        
            if (!esEdicionSegura) {
                 JOptionPane.showMessageDialog(this, 
                         "ERROR: No se puede editar el viaje porque tiene reservaciones activas (ACEPTADAS o EN ESPERA).", 
                         "Edicion Bloqueada", JOptionPane.ERROR_MESSAGE);
                 return; // Bloquea la navegación
            }
            
            // Si es seguro, navega a la pantalla de edicion.
            controlPantallas.mostrarEditarViaje();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                     "Error al verificar la edicion: " + e.getMessage(), 
                     "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarDatosViaje(ViajeDTO viaje) {
        try {
            txtOrigen.setText(viaje.getOrigen());
            txtDestino.setText(viaje.getDestino());
            txtFecha.setText(viaje.getFecha().toString());
            txtHora.setText(viaje.getHora().toString());
            txtClientes.setText(String.valueOf(viaje.getCantidadPasajeros()));

            txtOrigen.setEditable(false);
            txtDestino.setEditable(false);
            txtFecha.setEditable(false);
            txtHora.setEditable(false);
            txtClientes.setEditable(false);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar datos del viaje: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarViaje;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnEditarViaje;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtClientes;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
