/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion_crearRutaFrecuente;

import Controles.IControlPantallas;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 * pantalla que recolecta los datos proporcionados por el usuario para persistir una ruta frecuente
 * @author adell
 */
public class DatosRutaFrec extends javax.swing.JPanel {

    private final IControlPantallas controlPantallas;

    /**
     * Creates new form DatosRutaFrec
     */
    public DatosRutaFrec(IControlPantallas controlPantallas) {
        this.controlPantallas = controlPantallas;
        initComponents();
        configurarFiltroPrecio();
    }

    /**
     * Configura el filtro para el campo de precio
     */
    private void configurarFiltroPrecio() {
        ((AbstractDocument) PrecioTextField.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (string == null) {
                    return;
                }
                if (esEntradaValida(fb, offset, string, 0)) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text == null) {
                    return;
                }
                if (esEntradaValida(fb, offset, text, length)) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }

            private boolean esEntradaValida(FilterBypass fb, int offset, String text, int length) throws BadLocationException {
                String textoActual = fb.getDocument().getText(0, fb.getDocument().getLength());
                String textoNuevo = textoActual.substring(0, offset) + text + textoActual.substring(offset + length);

                // Permitir vacío o solo punto
                if (textoNuevo.isEmpty()) {
                    return true;
                }

                // Validar que solo contenga dígitos y un punto decimal
                if (!textoNuevo.matches("^\\d*\\.?\\d*$")) {
                    return false;
                }

                // No permitir más de un punto decimal
                if (textoNuevo.indexOf('.') != textoNuevo.lastIndexOf('.')) {
                    return false;
                }

                // Dividir en parte entera y decimal
                String[] partes = textoNuevo.split("\\.");

                // Limitar a 10 dígitos antes del punto decimal
                if (partes[0].length() > 10) {
                    return false;
                }

                // Limitar a 2 dígitos después del punto decimal
                if (partes.length > 1 && partes[1].length() > 2) {
                    return false;
                }

                return true;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nombreTField = new javax.swing.JTextField();
        destinoTField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaHora = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel1 = new javax.swing.JLabel();
        confirmarViajeBtn = new javax.swing.JButton();
        regresarMenuRutasBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PrecioTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        origenTField1 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 109, 182));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 109, 182));

        destinoTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoTFieldActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Destino:");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Origen:");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha y hora:");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        fechaHora.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RUTA");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        confirmarViajeBtn.setText("Siguiente");
        confirmarViajeBtn.setBorder(null);
        confirmarViajeBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        confirmarViajeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarViajeBtnActionPerformed(evt);
            }
        });

        regresarMenuRutasBtn.setText("Regresar");
        regresarMenuRutasBtn.setBorder(null);
        regresarMenuRutasBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        regresarMenuRutasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarMenuRutasBtnActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio:");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        PrecioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nombre:");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(regresarMenuRutasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmarViajeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinoTField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(origenTField1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombreTField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(origenTField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(destinoTField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PrecioTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarViajeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresarMenuRutasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 810, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void destinoTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoTFieldActionPerformed
    /**
     * boton que dispara el evento de confirmar viaje guardando los datos de la ruta frecuente
     * @param evt 
     */
    private void confirmarViajeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarViajeBtnActionPerformed
       
        String nombre = nombreTField.getText().trim();
        String origen = origenTField1.getText().trim();
        String destino = destinoTField.getText().trim();
        LocalDate fecha = fechaHora.getDatePicker().getDate();
        LocalTime hora = fechaHora.getTimePicker().getTime();
        String precioStr = PrecioTextField.getText().trim();

        // Validar campos vacíos
        if (nombre.isEmpty() || origen.isEmpty() || destino.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor complete todos los campos",
                    "Campos incompletos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validación: nombre solo debe contener letras, espacios y acentos
        if (!nombre.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
            JOptionPane.showMessageDialog(this,
                    "El Nombre solo debe contener letras.",
                    "Dato Invalido",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validación: origen y destino solo deben contener letras, espacios y acentos
        if (!origen.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
            JOptionPane.showMessageDialog(this,
                    "El Origen solo debe contener letras.",
                    "Dato Invalido",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!destino.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
            JOptionPane.showMessageDialog(this,
                    "El Destino solo debe contener letras.",
                    "Dato Invalido",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validación: origen y destino iguales
        if (origen.equalsIgnoreCase(destino)) {
            JOptionPane.showMessageDialog(this,
                    "El Origen y el Destino no pueden ser la misma ubicacion.",
                    "Dato Invalido",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar precio
        double precioBase;
        if (precioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor ingrese un precio.",
                    "Campo Requerido",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            precioBase = Double.parseDouble(precioStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El precio debe ser un numero valido.",
                    "Error de Formato",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validación: precio no puede ser 0 o negativo
        if (precioBase <= 0) {
            JOptionPane.showMessageDialog(this,
                    "El precio debe ser mayor a 0.",
                    "Precio Invalido",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar fecha y hora
        if (fechaHora.getDateTimeStrict() == null) {
            JOptionPane.showMessageDialog(this,
                    "Por favor seleccione una fecha y hora válida",
                    "Fecha inválida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que la fecha no sea en el pasado
        if (fechaHora.getDateTimeStrict().isBefore(java.time.LocalDateTime.now())) {
            JOptionPane.showMessageDialog(this,
                    "La fecha y hora de la ruta no puede ser en el pasado",
                    "Fecha inválida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Guardar los datos del viaje temporalmente (precio base 0, se calcula después)
        controlPantallas.GuardarDatosRutaFrec(nombre,origen, destino, fecha, hora);

        // Navegar a la siguiente pantalla
        controlPantallas.agregarParadaRuta(origen, precioBase);
        controlPantallas.mostrarParadasRuta();
    }//GEN-LAST:event_confirmarViajeBtnActionPerformed
    /**
     * boton que dispara el evento de devolver al usuario a la pantalla de menu rutas frecuente
     * @param evt 
     */
    private void regresarMenuRutasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarMenuRutasBtnActionPerformed
        // TODO add your handling code here:
              controlPantallas.mostrarMenuRutasFrecuentes();

    }//GEN-LAST:event_regresarMenuRutasBtnActionPerformed

    private void PrecioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PrecioTextField;
    private javax.swing.JButton confirmarViajeBtn;
    private javax.swing.JTextField destinoTField;
    private com.github.lgooddatepicker.components.DateTimePicker fechaHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreTField;
    private javax.swing.JTextField origenTField1;
    private javax.swing.JButton regresarMenuRutasBtn;
    // End of variables declaration//GEN-END:variables
}
