/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion_crearRutaFrecuente;

import Controles.ControlPantallas;
import Controles.IControlPantallas;
import dto.ParadaDTO;
import dto.RutaFrecuenteDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.HeadlessException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author adell
 */
public class MenuRutasFrecuentes extends javax.swing.JPanel {

    private final IControlPantallas controlPantallas;
    private RutaFrecuenteDTO RutaFrecuenteSeleccionadaDTO;

    /**
     * Creates new form MenuRutasFrecuentes
     */
    public MenuRutasFrecuentes(IControlPantallas controlPantallas, List<RutaFrecuenteDTO> rutas) {
        this.controlPantallas = controlPantallas;

        initComponents();
        mostrarRutas(rutas);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloLbl = new javax.swing.JLabel();
        panelContenedorRutas = new javax.swing.JPanel();
        registrarRutaBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 640));

        jPanel1.setBackground(new java.awt.Color(0, 109, 182));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 648));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 640));

        TituloLbl.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloLbl.setForeground(new java.awt.Color(255, 255, 255));
        TituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLbl.setText("RUTAS GUARDADAS");

        panelContenedorRutas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenedorRutasLayout = new javax.swing.GroupLayout(panelContenedorRutas);
        panelContenedorRutas.setLayout(panelContenedorRutasLayout);
        panelContenedorRutasLayout.setHorizontalGroup(
            panelContenedorRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        panelContenedorRutasLayout.setVerticalGroup(
            panelContenedorRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        registrarRutaBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registrarRutaBtn.setText("Registrar Ruta");
        registrarRutaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarRutaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(registrarRutaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(panelContenedorRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(TituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(registrarRutaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelContenedorRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registrarRutaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarRutaBtnActionPerformed
        // TODO add your handling code here:
        controlPantallas.mostrarDatosRutasFrecuente();
    }//GEN-LAST:event_registrarRutaBtnActionPerformed

    private void mostrarRutas(List listaRutas) {
        try {
            if (listaRutas != null) {

                JPanel panelInterno = new JPanel();
                panelInterno.setBackground(Color.WHITE);
                panelInterno.setLayout(new BoxLayout(panelInterno, BoxLayout.Y_AXIS));
                panelInterno.setPreferredSize(new Dimension(680, listaRutas.size() * 50));

                for (Object ruta : listaRutas) {
                    JPanel panelElemento = new JPanel();
                    panelElemento.setLayout(new BoxLayout(panelElemento, BoxLayout.X_AXIS));
                    panelElemento.setPreferredSize(new Dimension(660, 50));
                    panelElemento.setMaximumSize(new Dimension(660, 50));
                    panelElemento.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
                    panelElemento.setBackground(new Color(255, 255, 255));

                    JButton btnInfo = new JButton();
                    btnInfo.setFont(new Font("Dialog", Font.PLAIN, 14));
                    btnInfo.setBackground(Color.WHITE);
                    btnInfo.setAlignmentX(Component.CENTER_ALIGNMENT);
                    btnInfo.setHorizontalAlignment(SwingConstants.CENTER);
                    btnInfo.setPreferredSize(new Dimension(650, 40));
                    btnInfo.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
                    btnInfo.setText(ruta.toString());
                    btnInfo.addActionListener(e -> {
                        
                        
                        this.RutaFrecuenteSeleccionadaDTO = (dto.RutaFrecuenteDTO) ruta;
                        String origen = RutaFrecuenteSeleccionadaDTO.getOrigen();
                        String destino = RutaFrecuenteSeleccionadaDTO.getDestino();
                        LocalDate fecha = RutaFrecuenteSeleccionadaDTO.getFecha();
                        LocalTime hora = RutaFrecuenteSeleccionadaDTO.getHora();
                        double precioBase = RutaFrecuenteSeleccionadaDTO.getPrecioTotal();
                        controlPantallas.guardarDatosViaje(origen, destino, fecha, hora, precioBase);

                        List<ParadaDTO> paradas = RutaFrecuenteSeleccionadaDTO.getParadas();
                        for (ParadaDTO p : paradas) {
                            String destinoParada = p.getDirección();
                            double precioParada = p.getPrecio();

                            controlPantallas.agregarParada(destinoParada, precioParada);

                        }
                        
                        controlPantallas.mostrarSeleccionarVehiculoRuta();
                    });
                    panelElemento.add(btnInfo);
                    panelInterno.add(panelElemento);
                }
                JScrollPane scrollPane = new JScrollPane(panelInterno);
                scrollPane.setBackground(Color.WHITE);
                scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
                scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
                scrollPane.setPreferredSize(new Dimension(680, 458));
                panelContenedorRutas.removeAll();
                panelContenedorRutas.setLayout(new BorderLayout());
                panelContenedorRutas.add(scrollPane, BorderLayout.CENTER);
                panelContenedorRutas.revalidate();
                panelContenedorRutas.repaint();
            } else {
                JOptionPane.showMessageDialog(this, "No hay rutas registradas");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar rutas: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelContenedorRutas;
    private javax.swing.JButton registrarRutaBtn;
    // End of variables declaration//GEN-END:variables
}
