/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion_crearRutaFrecuente;

import Controles.ControlPantallas;
import Controles.IControlPantallas;
import dto.ParadaDTO;
import dto.RutaFrecuenteDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 * Clase que se encarga de mostrarle al usuario las rutas frecuentes registradas
 * asi como la opcion de empezar un nuevo registro
 *
 * @author adell
 */
public class MenuRutasFrecuentes extends javax.swing.JPanel {

    private final IControlPantallas controlPantallas;
    private RutaFrecuenteDTO RutaFrecuenteSeleccionadaDTO;

    /**
     * Creates new form MenuRutasFrecuentes
     */
    public MenuRutasFrecuentes(IControlPantallas controlPantallas, List<RutaFrecuenteDTO> rutas) {
        this.controlPantallas = controlPantallas;

        initComponents();
        ponerImg();

        datosConductor.setText(controlPantallas.nombreConductor().toString());
        datosConductor.setEditable(false);
        datosConductor.getCaret().setVisible(false);
        mostrarRutas(rutas);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloLbl = new javax.swing.JLabel();
        panelContenedorRutas = new javax.swing.JPanel();
        registrarRutaBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelFotoPerfil = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosConductor = new javax.swing.JTextArea();
        eliminarRutaBtn = new javax.swing.JButton();
        RegistrarViajeBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 640));

        jPanel1.setBackground(new java.awt.Color(0, 109, 182));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 648));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 640));

        TituloLbl.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloLbl.setForeground(new java.awt.Color(255, 255, 255));
        TituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLbl.setText("RUTAS GUARDADAS");

        panelContenedorRutas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenedorRutasLayout = new javax.swing.GroupLayout(panelContenedorRutas);
        panelContenedorRutas.setLayout(panelContenedorRutasLayout);
        panelContenedorRutasLayout.setHorizontalGroup(
            panelContenedorRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelContenedorRutasLayout.setVerticalGroup(
            panelContenedorRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        registrarRutaBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registrarRutaBtn.setText("Registrar Ruta");
        registrarRutaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarRutaBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        panelFotoPerfil.setBackground(new java.awt.Color(255, 255, 255));
        panelFotoPerfil.setName(""); // NOI18N

        javax.swing.GroupLayout panelFotoPerfilLayout = new javax.swing.GroupLayout(panelFotoPerfil);
        panelFotoPerfil.setLayout(panelFotoPerfilLayout);
        panelFotoPerfilLayout.setHorizontalGroup(
            panelFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelFotoPerfilLayout.setVerticalGroup(
            panelFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBar(null);

        datosConductor.setEditable(false);
        datosConductor.setBackground(new java.awt.Color(255, 255, 255));
        datosConductor.setColumns(20);
        datosConductor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        datosConductor.setRows(5);
        datosConductor.setBorder(null);
        datosConductor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        datosConductor.setFocusable(false);
        jScrollPane1.setViewportView(datosConductor);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFotoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFotoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        eliminarRutaBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        eliminarRutaBtn.setText("Eliminar Ruta");
        eliminarRutaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarRutaBtnActionPerformed(evt);
            }
        });

        RegistrarViajeBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RegistrarViajeBtn.setText("Registrar Viaje");
        RegistrarViajeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarViajeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(RegistrarViajeBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addComponent(registrarRutaBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eliminarRutaBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelContenedorRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(TituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(eliminarRutaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarRutaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RegistrarViajeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelContenedorRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * boton que dispara el eventos de mostrar la pantalla de datos rutas
     * frecuentes
     *
     * @param evt
     */
    private void registrarRutaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarRutaBtnActionPerformed
        // TODO add your handling code here:
        controlPantallas.mostrarDatosRutasFrecuente();
    }//GEN-LAST:event_registrarRutaBtnActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void eliminarRutaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarRutaBtnActionPerformed
        // TODO add your handling code here:
        if (RutaFrecuenteSeleccionadaDTO == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una ruta de la lista primero.", "Ruta no seleccionada", JOptionPane.WARNING_MESSAGE);
            return; // Detiene la ejecución si no hay selección.
        }
        String nombreRuta = RutaFrecuenteSeleccionadaDTO.getNombre();
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar la ruta con nombre: " + nombreRuta + "?",
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {

            controlPantallas.eliminarRuta(RutaFrecuenteSeleccionadaDTO);

            List<RutaFrecuenteDTO> listaActualizada = controlPantallas.obtenerListaRutas();
            mostrarRutas(listaActualizada);

        }


    }//GEN-LAST:event_eliminarRutaBtnActionPerformed

    private void RegistrarViajeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarViajeBtnActionPerformed
        // TODO add your handling code here:
        if (RutaFrecuenteSeleccionadaDTO == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una ruta de la lista primero.", "Ruta no seleccionada", JOptionPane.WARNING_MESSAGE);
            return; // Detiene la ejecución si no hay selección.
        }
        String origen = RutaFrecuenteSeleccionadaDTO.getOrigen();
        String destino = RutaFrecuenteSeleccionadaDTO.getDestino();
        LocalDate fecha = LocalDate.now();
        LocalTime hora = LocalTime.now();
        double precioBase = RutaFrecuenteSeleccionadaDTO.getPrecioTotal();
        controlPantallas.guardarDatosViaje(origen, destino, fecha, hora, precioBase);

        List<ParadaDTO> paradas = RutaFrecuenteSeleccionadaDTO.getParadas();
        for (ParadaDTO p : paradas) {
            String destinoParada = p.getDirección();
            double precioParada = p.getPrecio();

            controlPantallas.agregarParada(destinoParada, precioParada);

        }

        controlPantallas.mostrarSeleccionarVehiculoRuta();
    }//GEN-LAST:event_RegistrarViajeBtnActionPerformed

    /**
     * muesstra las rutas registradas del conductor
     *
     * @param listaRutas lista de rutas a mostrar
     */
    private void mostrarRutas(List listaRutas) {
        try {
            if (listaRutas != null) {

                JPanel panelInterno = new JPanel();
                panelInterno.setBackground(Color.WHITE);
                panelInterno.setLayout(new BoxLayout(panelInterno, BoxLayout.Y_AXIS));
                panelInterno.setPreferredSize(new Dimension(680, listaRutas.size() * 50));

                for (Object ruta : listaRutas) {
                    JPanel panelElemento = new JPanel();
                    panelElemento.setLayout(new BoxLayout(panelElemento, BoxLayout.X_AXIS));
                    panelElemento.setPreferredSize(new Dimension(660, 50));
                    panelElemento.setMaximumSize(new Dimension(660, 50));
                    panelElemento.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
                    panelElemento.setBackground(new Color(255, 255, 255));

                    JButton btnInfo = new JButton();
                    btnInfo.setFont(new Font("Dialog", Font.PLAIN, 14));
                    btnInfo.setBackground(Color.WHITE);
                    btnInfo.setAlignmentX(Component.CENTER_ALIGNMENT);
                    btnInfo.setHorizontalAlignment(SwingConstants.CENTER);
                    btnInfo.setPreferredSize(new Dimension(650, 40));
                    btnInfo.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
                    btnInfo.setText(ruta.toString());
                    btnInfo.addActionListener(e -> {

                        this.RutaFrecuenteSeleccionadaDTO = (dto.RutaFrecuenteDTO) ruta;

                    });
                    panelElemento.add(btnInfo);
                    panelInterno.add(panelElemento);
                }
                JScrollPane scrollPane = new JScrollPane(panelInterno);
                scrollPane.setBackground(Color.WHITE);
                scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
                scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
                scrollPane.setPreferredSize(new Dimension(680, 458));
                panelContenedorRutas.removeAll();
                panelContenedorRutas.setLayout(new BorderLayout());
                panelContenedorRutas.add(scrollPane, BorderLayout.CENTER);
                panelContenedorRutas.revalidate();
                panelContenedorRutas.repaint();
            } else {
                JOptionPane.showMessageDialog(this, "No hay rutas registradas");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar rutas: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void ponerImg() {
        File imagenC = new File("src\\main\\resources\\perfil.png");
        panelFotoPerfil.setLayout(new FlowLayout());
        ImageIcon icono = new ImageIcon(imagenC.getAbsolutePath());
        Image imgEscalada = icono.getImage().getScaledInstance(161, 161, Image.SCALE_SMOOTH);
        JLabel lblImagen = new JLabel(new ImageIcon(imgEscalada));
        lblImagen.setAlignmentX(CENTER_ALIGNMENT);

        panelFotoPerfil.add(lblImagen);
        panelFotoPerfil.revalidate();
        panelFotoPerfil.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrarViajeBtn;
    private javax.swing.JLabel TituloLbl;
    private javax.swing.JTextArea datosConductor;
    private javax.swing.JButton eliminarRutaBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelContenedorRutas;
    private javax.swing.JPanel panelFotoPerfil;
    private javax.swing.JButton registrarRutaBtn;
    // End of variables declaration//GEN-END:variables
}
