
package presentacion_gestionarSolicitudes;

import Controles.IControlPantallas;
import dto.ReservacionDTO;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author ferch
 */
public class DetalleReservaRuta extends javax.swing.JPanel {

    private final IControlPantallas controlPantallas;
    private final ReservacionDTO reserva;
    
    /**
     * Creates new form ProponerPrecio
     */
    public DetalleReservaRuta(IControlPantallas controlPantallas, ReservacionDTO reserva) {
        this.controlPantallas = controlPantallas;
        this.reserva = reserva;
        initComponents();
        cargarDatos();
    }
    
    private void cargarDatos() {
        jLabel3.setText("PROPONER PRECIO A: " + reserva.getPasajero().getNombre());
        txtPasajero.setText(reserva.getPasajero().getNombre());
        txtCalificacion.setText(String.valueOf(reserva.getPasajero().getCalificacion()));
        txtParadaPropuesta.setText(reserva.getParada().getDirección()); 
        
        // El precio se muestra para edición
        txtPrecioPropuesto.setText(String.valueOf(reserva.getPrecioTotal())); 
        
        txtPasajero.setEditable(false);
        txtCalificacion.setEditable(false);
        txtParadaPropuesta.setEditable(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        solicitudRutaPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPasajero = new javax.swing.JTextField();
        txtCalificacion = new javax.swing.JTextField();
        txtParadaPropuesta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrecioPropuesto = new javax.swing.JTextField();
        btnRechazar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEnviarPropuesta = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 109, 182));
        jPanel1.setMinimumSize(new java.awt.Dimension(1167, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 109, 182));

        solicitudRutaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pasajero: ");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Calificacion:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Parada Propuesta:");

        txtPasajero.setBackground(new java.awt.Color(255, 255, 255));
        txtPasajero.setForeground(new java.awt.Color(0, 0, 0));

        txtCalificacion.setBackground(new java.awt.Color(255, 255, 255));
        txtCalificacion.setForeground(new java.awt.Color(0, 0, 0));

        txtParadaPropuesta.setBackground(new java.awt.Color(255, 255, 255));
        txtParadaPropuesta.setForeground(new java.awt.Color(0, 0, 0));
        txtParadaPropuesta.addActionListener(this::txtParadaPropuestaActionPerformed);

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Precio propuesto:");

        txtPrecioPropuesto.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecioPropuesto.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecioPropuesto.addActionListener(this::txtPrecioPropuestoActionPerformed);

        javax.swing.GroupLayout solicitudRutaPanelLayout = new javax.swing.GroupLayout(solicitudRutaPanel);
        solicitudRutaPanel.setLayout(solicitudRutaPanelLayout);
        solicitudRutaPanelLayout.setHorizontalGroup(
            solicitudRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solicitudRutaPanelLayout.createSequentialGroup()
                .addGroup(solicitudRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(solicitudRutaPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(solicitudRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(solicitudRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(solicitudRutaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtParadaPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(solicitudRutaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrecioPropuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        solicitudRutaPanelLayout.setVerticalGroup(
            solicitudRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solicitudRutaPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(solicitudRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(solicitudRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(solicitudRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtParadaPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(solicitudRutaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPrecioPropuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        btnRechazar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRechazar.setText("Rechazar");
        btnRechazar.setBorder(null);
        btnRechazar.addActionListener(this::btnRechazarActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RESERVA RUTA");

        btnEnviarPropuesta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEnviarPropuesta.setText("Enviar Propuesta");
        btnEnviarPropuesta.setBorder(null);
        btnEnviarPropuesta.addActionListener(this::btnEnviarPropuestaActionPerformed);

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(116, 116, 116)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(solicitudRutaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(642, Short.MAX_VALUE)
                    .addComponent(btnEnviarPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(solicitudRutaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(499, Short.MAX_VALUE)
                    .addComponent(btnEnviarPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 870, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1069, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarActionPerformed
        try {
            controlPantallas.rechazarSolicitud(reserva);
            JOptionPane.showMessageDialog(this, "Reserva rechazada. Se notificos al pasajero.", "Reserva Rechazada", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al rechazar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        controlPantallas.mostrarGestionSolicitudes(reserva.getViaje().getId());
    }//GEN-LAST:event_btnRechazarActionPerformed

    private void btnEnviarPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPropuestaActionPerformed
        try {
            String precioStr = txtPrecioPropuesto.getText().trim();

            if (precioStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El precio es obligatorio.", "Campo Requerido", JOptionPane.WARNING_MESSAGE);
                return;
            }

            double nuevoPrecio;
            try {
                nuevoPrecio = Double.parseDouble(precioStr);
                if (nuevoPrecio <= 0) {
                    JOptionPane.showMessageDialog(this, "El precio debe ser un número positivo.", "Dato Inválido", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Crear el DTO con el precio propuesto
            ReservacionDTO reservacionPropuesta = new ReservacionDTO();
            reservacionPropuesta.setId(reserva.getId()); 
            reservacionPropuesta.setViaje(reserva.getViaje());
            reservacionPropuesta.setParada(reserva.getParada()); 
            reservacionPropuesta.setPasajero(reserva.getPasajero());

            reservacionPropuesta.setPrecioTotal(nuevoPrecio); // Nuevo precio propuesto

            //Llama a la capa de control para guardar la propuesta
            controlPantallas.proponerPrecio(reservacionPropuesta);

            JOptionPane.showMessageDialog(this,
                    "Propuesta de precio enviada al pasajero.\nLa reserva será confirmada automáticamente si el pasajero acepta.",
                    "Propuesta Enviada",
                    JOptionPane.INFORMATION_MESSAGE);

            // 3. Regresa a la pantalla de gestión de solicitudes
            controlPantallas.mostrarGestionSolicitudes(reserva.getViaje().getId());

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al proponer precio: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEnviarPropuestaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        controlPantallas.mostrarGestionSolicitudes(reserva.getViaje().getId());
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtParadaPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParadaPropuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParadaPropuestaActionPerformed

    private void txtPrecioPropuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioPropuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioPropuestoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarPropuesta;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel solicitudRutaPanel;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtParadaPropuesta;
    private javax.swing.JTextField txtPasajero;
    private javax.swing.JTextField txtPrecioPropuesto;
    // End of variables declaration//GEN-END:variables
}
