
package presentacion_gestionarSolicitudes;

import Controles.IControlPantallas;
import dto.ReservacionDTO;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ferch
 */
public class DetalleReservaEstandar extends javax.swing.JPanel {
    
    private final IControlPantallas controlPantallas;
    private final ReservacionDTO reserva;
  
    /**
     * Creates new form detalleReservaRuta
     */
    public DetalleReservaEstandar(IControlPantallas controlPantallas, ReservacionDTO reserva) {
        this.controlPantallas = controlPantallas;
        this.reserva = reserva;
        initComponents();
        cargarDatos();
    }

    private void cargarDatos() {
        Color white = new java.awt.Color(255, 255, 255);
        Color blue = new java.awt.Color(0, 109, 182);
        
        solicitudEstandarPanel.setBackground(blue);
        jLabel6.setForeground(white); // Pasajero
        jLabel8.setForeground(white); // Calificacion
        jLabel9.setForeground(white); // Precio
        jLabel10.setForeground(white); // punto de encuentro
        
        txtPasajero.setBackground(blue);
        txtPasajero.setForeground(white);
        txtCalificacion.setBackground(blue);
        txtCalificacion.setForeground(white);
        txtDestino.setBackground(blue);
        txtDestino.setForeground(white);
        txtPrecio.setBackground(blue);
        txtPrecio.setForeground(white);
        
        String nombrePasajero = (reserva.getPasajero() != null && reserva.getPasajero().getNombre() != null) 
                                ? reserva.getPasajero().getNombre() 
                                : "Carlos Perez";
        String calificacionPasajero = (reserva.getPasajero() != null) ? String.valueOf(reserva.getPasajero().getCalificacion()) : "N/D";

       // Lógica para el Punto de Encuentro (P. Encuentro)
        String paradaRecogida;
        
        if (reserva.getParada() != null && reserva.getParada().getDirección() != null) {
            paradaRecogida = reserva.getParada().getDirección();
            
        } else if (reserva.getViaje() != null && reserva.getViaje().getOrigen() != null) {
            paradaRecogida = reserva.getViaje().getOrigen();
            
        } else {
            // Caso 3: Fallback general.
            paradaRecogida = "Parada No Definida"; 
        }

        txtPasajero.setText(nombrePasajero);
        txtCalificacion.setText(calificacionPasajero);
        txtDestino.setText(paradaRecogida);
        txtPrecio.setText(String.format("$%.2f", reserva.getPrecioTotal()));
        
        txtPasajero.setEditable(false);
        txtCalificacion.setEditable(false);
        txtDestino.setEditable(false);
        txtPrecio.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        solicitudEstandarPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPasajero = new javax.swing.JTextField();
        txtCalificacion = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnRechazar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 109, 182));
        jPanel1.setMinimumSize(new java.awt.Dimension(1167, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 109, 182));

        solicitudEstandarPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pasajero: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Calificacion:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Precio:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("P.Encuentro:");

        txtPasajero.setBackground(new java.awt.Color(255, 255, 255));
        txtPasajero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPasajero.setForeground(new java.awt.Color(255, 255, 255));
        txtPasajero.setBorder(null);

        txtCalificacion.setBackground(new java.awt.Color(255, 255, 255));
        txtCalificacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCalificacion.setForeground(new java.awt.Color(0, 0, 0));
        txtCalificacion.setBorder(null);

        txtDestino.setBackground(new java.awt.Color(255, 255, 255));
        txtDestino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDestino.setForeground(new java.awt.Color(0, 0, 0));
        txtDestino.setBorder(null);

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.setBorder(null);

        javax.swing.GroupLayout solicitudEstandarPanelLayout = new javax.swing.GroupLayout(solicitudEstandarPanel);
        solicitudEstandarPanel.setLayout(solicitudEstandarPanelLayout);
        solicitudEstandarPanelLayout.setHorizontalGroup(
            solicitudEstandarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solicitudEstandarPanelLayout.createSequentialGroup()
                .addGroup(solicitudEstandarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(solicitudEstandarPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel9))
                    .addGroup(solicitudEstandarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solicitudEstandarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(solicitudEstandarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(37, 37, 37)
                .addGroup(solicitudEstandarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDestino)
                    .addComponent(txtPrecio)
                    .addComponent(txtPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalificacion))
                .addGap(234, 234, 234))
        );
        solicitudEstandarPanelLayout.setVerticalGroup(
            solicitudEstandarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solicitudEstandarPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(solicitudEstandarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(solicitudEstandarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(solicitudEstandarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(solicitudEstandarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        btnRechazar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRechazar.setText("Rechazar");
        btnRechazar.setBorder(null);
        btnRechazar.addActionListener(this::btnRechazarActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RESERVA ESTANDAR");

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(solicitudEstandarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(642, Short.MAX_VALUE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(solicitudEstandarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(499, Short.MAX_VALUE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 870, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1069, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarActionPerformed
      try {
        controlPantallas.rechazarSolicitud(reserva);
        JOptionPane.showMessageDialog(this, "Reserva rechazada. Se notifico al pasajero.", "Reserva Rechazada", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al rechazar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    controlPantallas.mostrarSeleccionarViajeGestion();
      

    }//GEN-LAST:event_btnRechazarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
      try {
        controlPantallas.aceptarSolicitud(reserva);
        JOptionPane.showMessageDialog(this, "Reserva aceptada. Se notifico al pasajero.", "Reserva Aceptada", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al aceptar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    controlPantallas.mostrarSeleccionarViajeGestion();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
            controlPantallas.mostrarGestionSolicitudes(reserva.getViaje().getId());
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel solicitudEstandarPanel;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtPasajero;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
