
package presentacion_gestionarSolicitudes;

import Controles.IControlPantallas;
import dto.ViajeDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author ferch
 */
public class SeleccionarViajeGestion extends javax.swing.JPanel {
private final IControlPantallas controlPantallas;
    private final List<ViajeDTO> viajes;
    /**
     * Creates new form ViajesSolicitudes
     */
     public SeleccionarViajeGestion(IControlPantallas controlPantallas, List<ViajeDTO> viajes) {
        this.controlPantallas = controlPantallas;
        this.viajes = viajes;
        initComponents();
        mostrarViajes(viajes);
    }
     
     // Método para dibujar la lista de viajes en el panel contenedor
    private void mostrarViajes(List<ViajeDTO> listaViajes) {
        try {
            JPanel panelInterno = new JPanel();
            panelInterno.setBackground(Color.WHITE);
            panelInterno.setLayout(new BoxLayout(panelInterno, BoxLayout.Y_AXIS));

            int rowHeight = 50;
            int preferredHeight = Math.max(250, listaViajes.size() * rowHeight);

            panelInterno.setPreferredSize(new Dimension(740, preferredHeight));

            if (listaViajes.isEmpty()) {
                panelInterno.add(new JLabel("No tienes viajes activos para gestionar solicitudes."));
            } else {
                for (ViajeDTO viaje : listaViajes) {
                    JPanel panelElemento = new JPanel();
                panelElemento.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
                panelElemento.setPreferredSize(new Dimension(720, rowHeight));
                panelElemento.setMaximumSize(new Dimension(720, rowHeight));
                panelElemento.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(200, 200, 200)));
                panelElemento.setBackground(new Color(255, 255, 255)); 

                JButton btnInfo = new JButton();
                btnInfo.setFont(new Font("Dialog", Font.PLAIN, 14)); 
                btnInfo.setBackground(Color.WHITE);
                btnInfo.setForeground(Color.BLACK); 
                btnInfo.setHorizontalAlignment(SwingConstants.LEFT);
                btnInfo.setPreferredSize(new Dimension(700, 40)); 
                btnInfo.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10)); 
                
                String infoTexto = String.format("Origen: %s | Destino: %s | Fecha: %s",
                                                viaje.getOrigen(), viaje.getDestino(), viaje.getFecha());
                btnInfo.setText(infoTexto);
                    btnInfo.addActionListener(e -> {
                        controlPantallas.mostrarGestionSolicitudes(viaje.getId());
                    });

                    panelElemento.add(btnInfo);
                    panelInterno.add(panelElemento);
                }
            }
           

            JScrollPane scrollPane = new JScrollPane(panelInterno);
            scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
            scrollPane.setPreferredSize(new Dimension(750, 400));
            scrollPane.setBackground(Color.WHITE);
            
            panelContenedorViajes.removeAll();
            panelContenedorViajes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
            panelContenedorViajes.add(scrollPane);
            panelContenedorViajes.revalidate();
            panelContenedorViajes.repaint();

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar viajes: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        regresarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panelContenedorViajes = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(0, 109, 182));
        jPanel1.setMinimumSize(new java.awt.Dimension(1167, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 109, 182));

        regresarBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        regresarBtn.setText("Regresar");
        regresarBtn.setBorder(null);
        regresarBtn.addActionListener(this::regresarBtnActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Viajes con solicitudes");

        javax.swing.GroupLayout panelContenedorViajesLayout = new javax.swing.GroupLayout(panelContenedorViajes);
        panelContenedorViajes.setLayout(panelContenedorViajesLayout);
        panelContenedorViajesLayout.setHorizontalGroup(
            panelContenedorViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        panelContenedorViajesLayout.setVerticalGroup(
            panelContenedorViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(773, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelContenedorViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(panelContenedorViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 980, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1069, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        controlPantallas.mostrarMenuConductor();
    }//GEN-LAST:event_regresarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelContenedorViajes;
    private javax.swing.JButton regresarBtn;
    // End of variables declaration//GEN-END:variables
}
