/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion_registrarVehiculo;

import Controles.IControlPantallas;
import dto.VehiculoDTO;
import dto.ViajeDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author adell
 */
public class menuVehiculosConductor extends javax.swing.JPanel {

    private final IControlPantallas controlPantallas;
    private VehiculoDTO vehiculoSeleccionadoDTO;

    /**
     * Creates new form menuVehiculosConductor
     */
    public menuVehiculosConductor(IControlPantallas controlPantallas, List<VehiculoDTO> vehiculo) {
        this.controlPantallas = controlPantallas;
        initComponents();
        mostrarVehiculos(vehiculo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TituloLbl = new javax.swing.JLabel();
        panelContenedorVehiculos = new javax.swing.JPanel();
        registrarRutaBtn = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 640));

        jPanel2.setBackground(new java.awt.Color(0, 109, 182));
        jPanel2.setMinimumSize(new java.awt.Dimension(1080, 648));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 640));

        TituloLbl.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloLbl.setForeground(new java.awt.Color(255, 255, 255));
        TituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLbl.setText("VEHICULOS GUARDADOS");

        panelContenedorVehiculos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenedorVehiculosLayout = new javax.swing.GroupLayout(panelContenedorVehiculos);
        panelContenedorVehiculos.setLayout(panelContenedorVehiculosLayout);
        panelContenedorVehiculosLayout.setHorizontalGroup(
            panelContenedorVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        panelContenedorVehiculosLayout.setVerticalGroup(
            panelContenedorVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        registrarRutaBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrarRutaBtn.setText("Registrar Vehiculo");
        registrarRutaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarRutaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(registrarRutaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelContenedorVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addComponent(registrarRutaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelContenedorVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registrarRutaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarRutaBtnActionPerformed
        // TODO add your handling code here:
        controlPantallas.mostrarDatosVehiculo();
    }//GEN-LAST:event_registrarRutaBtnActionPerformed

    private void mostrarVehiculos(List listaVehiculos) {
        try {
            if (listaVehiculos != null) {

                JPanel panelInterno = new JPanel();
                panelInterno.setLayout(new BoxLayout(panelInterno, BoxLayout.Y_AXIS));
                panelInterno.setPreferredSize(new Dimension(740, listaVehiculos.size() * 50));
                panelInterno.setBackground(Color.WHITE);
                for (Object vehiculo : listaVehiculos) {
                    JPanel panelElemento = new JPanel();
                    panelElemento.setLayout(new BoxLayout(panelElemento, BoxLayout.X_AXIS));
                    panelElemento.setPreferredSize(new Dimension(740, 50));
                    panelElemento.setMaximumSize(new Dimension(740, 50));
                    panelElemento.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
                    panelElemento.setBackground(new Color(255, 255, 255));

                    JButton btnInfo = new JButton();
                    btnInfo.setFont(new Font("Dialog", Font.PLAIN, 14));
                    btnInfo.setBackground(Color.WHITE);
                    btnInfo.setAlignmentX(Component.CENTER_ALIGNMENT);
                    btnInfo.setHorizontalAlignment(SwingConstants.CENTER);
                    btnInfo.setPreferredSize(new Dimension(700, 40));
                    btnInfo.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
                    btnInfo.setText(vehiculo.toString().formatted());
                    btnInfo.addActionListener(e -> {
                        this.vehiculoSeleccionadoDTO = (dto.VehiculoDTO) vehiculo;
                    });

                    panelElemento.add(btnInfo);
                    panelInterno.add(panelElemento);
                }
                JScrollPane scrollPane = new JScrollPane(panelInterno);
                scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
                scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
                scrollPane.setPreferredSize(new Dimension(770, 362));
                scrollPane.setBackground(Color.WHITE);
                panelContenedorVehiculos.removeAll();
                panelContenedorVehiculos.setLayout(new BorderLayout());
                panelContenedorVehiculos.add(scrollPane, BorderLayout.CENTER);
                panelContenedorVehiculos.revalidate();
                panelContenedorVehiculos.repaint();
            } else {
                JOptionPane.showMessageDialog(this, "No hay vehiculos registrados");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar vehículos: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelContenedorVehiculos;
    private javax.swing.JButton registrarRutaBtn;
    // End of variables declaration//GEN-END:variables
}
